#!/usr/bin/env python3
"""Whose spurs are they? Vary the transmit power and watch what the ratio does.

A spur generated in the TRANSMITTER tracks the carrier: drop the carrier 10 dB
and the spur drops 10 dB, so the ratio in dBc is constant. A spur generated by
the RECEIVER's own non-linearity grows faster than the signal, so backing the
signal off IMPROVES the dBc ratio. One sweep separates the two, and without it
every spur on the plot is unattributed.
"""
import os, subprocess, sys, json, numpy as np, board as B, chain, dsp

HOST, BLO, TONE, CH = os.environ.get("BOARD", "192.168.2.1"), 866_500_000, 600_000, 1

def cap(n=1 << 20):
    subprocess.run([sys.executable, "hackrf_cap.py", "--freq", str(BLO - chain.OFFSET),
                    "--rate", str(chain.HACK_FS), "--n", str(n), "--out", "/tmp/s.cf32",
                    "--lna", "24", "--vga", "24", "--bw", str(chain.HACK_BW)],
                   check=True, capture_output=True)
    return np.fromfile("/tmp/s.cf32", dtype=np.complex64)

rows = []
b = B.Board(HOST)
try:
    b.configure_tx(BLO, 4_000_000, bw=4_000_000)
    n = 4096; k = round(TONE * n / 4e6)
    iq = np.exp(2j * np.pi * k * np.arange(n) / n); tone = k * 4e6 / n
    print(f"  tone at {tone/1e3:+.1f} kHz; spurs looked for at tone +-1 MHz (the board's fs/4)\n")
    print(f"  {'atten':>6} {'carrier':>9} {'spur -1MHz':>11} {'spur +1MHz':>11} "
          f"{'worst dBc':>10} {'rx spur -1.5MHz':>16}")
    for atten in (-36, -30, -24, -20, -16):
        b.transmit(iq, atten, pair=CH, cyclic=True, scale=0.9)
        y, fsw = chain.receive(cap())
        f, p, _ = dsp.hi_dr_psd(y, fsw, nfft=1 << 15)
        def peak(fc, w=30e3):
            m = np.abs(f - fc) < w
            return float(p[m].max())
        c = peak(tone)
        lo, hi = peak(tone - 1e6), peak(tone + 1e6)
        rxs = peak(-1.5e6)
        rows.append(dict(atten=atten, carrier=c, spur_lo=lo, spur_hi=hi,
                         worst_dbc=max(lo, hi) - c, rx_spur=rxs))
        print(f"  {atten:6.0f} {c:9.1f} {lo:11.1f} {hi:11.1f} {max(lo,hi)-c:10.1f} {rxs:16.1f}")
        b.stop()
finally:
    print("\n  stop:", b.stop()); b.close()
    json.dump(rows, open("results/spurs.json", "w"), indent=1)
